name: Tim Bedard
author: Tim Bedard
email: info@timbedard.com
description: > # this means to ignore newlines until "baseurl:"
  musician and software developer
twitter_username: timsical
github_username:  timbedard
linkedin_username: timbedard

# --- Where things are --- #
# source:          .
# destination:     ./_site
# collections_dir: .
# plugins_dir:     _plugins
# layouts_dir:     _layouts
# data_dir:        _data
# includes_dir:    _includes
collections:
  # posts:
  #   output: true
  cv:
    output: true

# --- Handling Reading --- #
# safe:              false
# include:           [".htaccess"]
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - sass
  - watch.sh
  - style.scss
  - bootstrap.scss
# keep_files:        [".git", ".svn"]
# encoding:          "utf-8"
# markdown_ext:      "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: true

# --- Filtering Content --- #
# show_drafts: null
# limit_posts: 0
# future:      false
# unpublished: false

# --- Plugins --- #
# whitelist: []
plugins:  [jekyll-paginate]
paginate: 10

# --- Conversion --- #
# markdown:    kramdown
# highlighter: rouge
# lsi:         false
# excerpt_separator: "\n\n"
# incremental: false

# --- Serving --- #
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: "" # does not include hostname
# show_dir_listing: false

# --- Outputting --- #
# permalink:     date
# paginate_path: /page:num
# timezone:      null

# quiet:    false
# verbose:  false
defaults:
  - scope:
      path: ""
      type: cv
    values:
      layout: cv-item

# liquid:
#   error_mode: warn

# --- Markdown Processors --- #
# rdiscount:
#   extensions: []

# redcarpet:
#   extensions: []

# kramdown:
#   auto_ids:       true
#   entity_output:  as_char
#   toc_levels:     1..6
#   smart_quotes:   lsquo,rsquo,ldquo,rdquo
#   input:          GFM
#   hard_wrap:      false
#   footnote_nr:    1
